# Generated by Django 5.2.6 on 2025-09-28 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_add_report_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ResidentReport already exists from migration 0009, so we only need to alter it
        migrations.RenameField(
            model_name='residentreport',
            old_name='message',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='residentreport',
            name='description',
            field=models.TextField(default='Description non fournie', verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='residentreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='residentreport',
            name='category',
            field=models.CharField(choices=[('MAINTENANCE', 'Entretien / Réparation'), ('SECURITY', 'Sécurité / Surveillance'), ('COMMUNITY', 'Communauté / Voisinage'), ('CLEANLINESS', 'Propreté / Nettoyage'), ('NOISE', 'Bruit / Troubles'), ('UTILITIES', 'Services / Équipements'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='residentreport',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('ARCHIVED', 'Archivé')], default='NEW', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterModelOptions(
            name='residentreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rapport de résident', 'verbose_name_plural': 'Rapports de résidents'},
        ),
    ]
