# Generated by Django 5.2.6 on 2026-02-26 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_remove_notification_amount_remove_notification_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='residentreport',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localisation (optionnelle)'),
        ),
        migrations.AlterField(
            model_name='residentreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Photo (optionnelle)'),
        ),
        migrations.AlterField(
            model_name='residentreport',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du rapport'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('EMAIL', 'Email'), ('PDF', 'PDF'), ('SMS', 'SMS')], default='EMAIL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('VIEWED', 'Vu'), ('FAILED', 'Échoué')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reminders/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERADMIN', 'SYNDIC']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders_sent', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.document')),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'RESIDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reminders_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['-created_at'],
            },
        ),
    ]
