# Generated by Django 5.2.6 on 2026-03-24 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_alter_residentreport_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['date_depense'], name='finance_dep_date_de_ed75e2_idx'),
        ),
        migrations.AddIndex(
            model_name='depense',
            index=models.Index(fields=['categorie'], name='finance_dep_categor_0906d9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['resident', 'is_paid'], name='finance_doc_residen_8416eb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['resident', 'is_archived'], name='finance_doc_residen_2b4971_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date'], name='finance_doc_date_911669_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='finance_doc_created_1c8e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='finance_not_notific_0a51c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='finance_not_priorit_d36781_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'created_at'], name='finance_not_is_acti_c50a46_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'is_active'], name='finance_not_is_read_1cff96_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['document', 'payment_date'], name='finance_pay_documen_67f1be_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='finance_pay_payment_72f761_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_verified'], name='finance_pay_is_veri_511ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='residentreport',
            index=models.Index(fields=['resident', 'status'], name='finance_res_residen_660dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='residentreport',
            index=models.Index(fields=['status', 'created_at'], name='finance_res_status_2259ff_idx'),
        ),
        migrations.AddIndex(
            model_name='residentreport',
            index=models.Index(fields=['category'], name='finance_res_categor_be855d_idx'),
        ),
    ]
