# Generated by Django 5.2.6 on 2026-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'immeuble")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('total_apartments', models.PositiveIntegerField(verbose_name="Nombre d'appartements")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Immeuble',
                'verbose_name_plural': 'Immeubles',
                'ordering': ['name'],
            },
        ),
    ]
